language: generic
before_install:
- mkdir -p ~/bin
- cd ~/bin
- echo will download packer ${PACKERVER}
- curl -o packer.zip https://releases.hashicorp.com/packer/${PACKERVER}/packer_${PACKERVER}_linux_amd64.zip
- unzip packer.zip
- chmod +x packer
script:
- for template in *.json ; do ~/bin/packer validate ${template}; done
